stages:
  - build

before_script:
  - 'configure.py'

build_2017:
  artifacts:
    paths:
    - bin/
    expire_in: 1 week
  variables:
    CMAKE_GENERATOR: 'Visual Studio 15 2017'
  stage: build
  script:
  - build.py
  tags:
  - msvc2017
  
build_2019:
  artifacts:
    paths:
    - bin/
    expire_in: 1 week
  variables:
    CMAKE_GENERATOR: 'Visual Studio 16 2019'
  stage: build
  script:
  - build.py
  tags:
  - msvc2019
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive